name: Release Plugin

on:
  push:
    tags:
      - '*'

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install build tool
        run: |
          pip install -U build
      - name: Build artifacts
        run: |
          python -m build --sdist --wheel .
      - name: Upload to Pypi
        run: |
          pip install twine
          twine upload --username __token__ --password ${{ secrets.PYPI_TOKEN }} dist/*
